# -*- coding: utf-8 -*-
"""fraud_detection_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ab-36xbgu5hMB_yI1nDpVkIyK4um_3Ye
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

data = pd.read_csv("creditcard.csv")

print(data.shape)

print(data.isnull().sum())

data = data.dropna()

print(data["Class"].value_counts())

X = data.drop("Class", axis=1)
y = data["Class"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Scale features
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train model
model = LogisticRegression(max_iter=10000, class_weight="balanced")

model.fit(X_train_scaled, y_train)

predictions = model.predict(X_test_scaled)

fraud_probability = model.predict_proba(X_test_scaled)[:,1]

# Predict fraud class
predictions = model.predict(X_test_scaled)

print(predictions[:10])

# Probability of fraud
fraud_probability = model.predict_proba(X_test_scaled)[:,1]

print(fraud_probability[:10])

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)

print("Model Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, predictions)

print(cm)

from sklearn.metrics import classification_report

print(classification_report(y_test, predictions))

risk_level = []

for p in fraud_probability:
    if p > 0.8:
        risk_level.append("High Risk")
    elif p > 0.4:
        risk_level.append("Medium Risk")
    else:
        risk_level.append("Low Risk")
print(risk_level[:10])

results = X_test.copy()

results["actual_fraud"] = y_test
results["predicted_fraud"] = predictions
results["fraud_probability"] = fraud_probability
results["risk_level"] = risk_level

print(results.head())

results.to_csv("fraud_predictions.csv", index=False)

print("File exported successfully")

from google.colab import files
files.download("fraud_predictions.csv")

